# Generated by Django 5.2.7 on 2025-10-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_studentprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
