# Generated by Django 5.2.7 on 2025-10-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_activity_end_time_activity_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(default='ไม่ระบุ', max_length=100),
        ),
    ]
