# Generated by Django 5.2.7 on 2025-10-08 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_alter_activity_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='image',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='image',
        ),
    ]
