# Generated by Django 5.2.7 on 2025-10-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_remove_club_image_remove_studentprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
