# Generated by Django 5.2.7 on 2025-10-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_activity_image_club_image_studentprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='clubs',
            field=models.ManyToManyField(related_name='members', to='university.club'),
        ),
    ]
