# Generated by Django 5.2.7 on 2025-10-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_alter_member_clubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='members', to='university.club'),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('LEADER', 'Leader'), ('MEMBER', 'Member')], default='MEMBER', max_length=50),
        ),
    ]
