# Generated by Django 5.2.7 on 2025-10-09 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_alter_member_clubs_alter_member_join_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/')),
                ('status', models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติ'), ('REJECTED', 'ปฏิเสธ')], default='PENDING', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.account')),
            ],
        ),
    ]
