# Generated by Django 5.2.7 on 2025-10-11 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_clubrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('LEADER', 'Leader'), ('MEMBER', 'Member')], default='MEMBER', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติ'), ('REJECTED', 'ปฏิเสธ')], default='PENDING', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.account')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.club')),
            ],
        ),
    ]
