# Generated by Django 5.2.7 on 2025-10-11 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_memberrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.account'),
        ),
    ]
