# Generated by Django 5.2.7 on 2025-10-15 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_club_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubrequest',
            name='requested_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university.account'),
        ),
    ]
